### ISSUE TITLE
Fatal error: Call to undefined function apcu_fetch() in /Users/.../.composer/global/weprovide/valet-plus/vendor/weprovide/valet-plus/server.php on line 37

### ISSUE THREAD

**Issue by philcollinus** [weprovide/valet-plus#249]
I know that this has been asked many times before, but those tickets have been closed and all the items I have tried do not work.

This occurred randomly after doing a 'valet install'. The system has been working for months without issue.

Here is what I have tried so far:
- Uninstalled and reinstalled PHP (all versions) using Brew
- Tried to use 'valet use X.XX' for all versions of PHP
- Have restarted my computer about 100 times
- Have unlinked and --force linked every version
- Have made sure both my CLI and valet setup were using 7.1 (the version I am trying to continue to use)
- I have also installed the apcu module and apcu_bc module

Any assistance from people that have had success fixing this issue?

Its been a few days now without my dev environment and I don't want to go back to my other methods of local dev as I have gotten so used to this one.

**Comment by jmcerrejon** [comment]
Same problem here even with 7.2

**Comment by ceesvanegmond** [comment]
Same problem here.

**Comment by philcollinus** [comment]
Yes the biggest issue is that this is happening with every version for me. So version switching, even to a lower version, does not fix this.

**Comment by jellesiderius** [comment]
When this happens, i just switch between PHP versions. Should be fixed tho.

**Comment by philcollinus** [comment]
Yeah I have tried switching. I installed new versions, I have completely uninstalled all PHP versions and reinstalled them. Still get the same issue unfortunately.

Almost 1.5 weeks with no Valet + working on this computer sucks. 

Hopefully I will find a fix soon, since their doesn't seem to be any response on this thread for fixes.

**Comment by regularlabs** [comment]
I have the same issue.

Only php@7.1 works.

Whenever I try to do a `valet use 5.6` or `valet use 7.2`, the `php -v` still says it is using php 7.1.
And loading php files in the browser, give the mentioned error:
```
Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in /Users/.../.composer/vendor/weprovide/valet-plus/server.php:37 Stack trace: #0 {main} thrown in /Users/.../.composer/vendor/weprovide/valet-plus/server.php on line 37
```

It looks like the symlinks are not being handled correctly or something.

Maybe this has to do with incorrect $PATH settings in the `.bash_profile` (for bash) or `.zshrc` (for zsh)?

I have this in my `.zshrc`:
```
export PATH="/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="vendor/bin:$PATH"
export PATH="$(brew --prefix)/bin:$PATH"
```

**Comment by regularlabs** [comment]
PS: I have gone trough pretty much all the process mentioned anywhere in other tickets on this.
Reinstalled php versions & valet-plus (in different orders). Removed `/usr/local/etc/php`folder. Done the `pecl uninstall` stuff. Done `valet fix` and `valet install` at pretty much any imaginable stage. Restarted a zillion times.

Still php 5.6 and 7.2 don't work and I need to stick with `valet use 7.1` (or just don't install the other 2).

**Comment by regularlabs** [comment]
When I do a `which php` (even after `valet use 5.6` or `valet use 7.2`, I always get:
```
/usr/local/opt/php@7.1/bin/php
```

**Comment by regularlabs** [comment]
Ah, FINALLY!!!!

Ok, sorry for the many posts here.

So I found out this was at the end of my `.zshrc` file:
```
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/php@7.1/bin:$PATH"
export PATH="/usr/local/opt/php@7.1/sbin:$PATH"
```
I removed that, did a `. ~/.zshrc` and everything is working now!

**Comment by samgranger** [comment]
Closing issue.
