### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in 

### ISSUE THREAD

**Issue by Jikke** [weprovide/valet-plus#284]
After solving many other issues installing from fresh... I finally bumped into this one. Tried all else that can be found in the issue, restarting, re-installing. Driving me pretty crazy by now. 

Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in /Users/jikke/.composer/vendor/weprovide/valet-plus/server.php:37 Stack trace: #0 {main} thrown in /Users/jikke/.composer/vendor/weprovide/valet-plus/server.php on line 37

Does anyone know what to do?

**Comment by rafaelstz** [comment]
Run these commands:

```bash
pecl install apcu_bc
valet fix && valet install
```

Force to quit your terminal using **Command + Q**, then open it again.

**Comment by diazwatson** [comment]
```
No releases available for package "pecl.php.net/apcu_bc"
install failed
```

**Comment by diazwatson** [comment]
In my case there was a problem with openssl.

`pecl` tries to connect to `pecl.php.net/apcu_bc` but it seems like the **`http`** is not longer available. Then it tries to connect using **`https`** but for that, it needs openssl.

I fixed my issue by reinstalling openssl:
```
brew reinstall openssl
```

**Comment by Treggats** [comment]
I tried the same as @diazwatson suggested, didn't fix the issue for me

**Comment by diazwatson** [comment]
@Treggats have you tried executing all the commands @rafaelstz suggested?
```
brew reinstall openssl
pecl install apcu_bc
valet fix && valet install
```

**Comment by Treggats** [comment]
@diazwatson yes I have, even rebooted my mac a couple times to no avail

**Comment by diazwatson** [comment]
and what error do you get?
what are you doing to reproduce the error?

**Comment by Treggats** [comment]
From memory, end of the workday here.

```
valet stop
valet uninstall
composer global remove laravel/valet
composer global require weprovide/valet-plus
composer global update
```

Pretty much followed the readme and the steps provided here. But had to revert back because this isn't exactly billable :) I'll try again at a later time

**Comment by diazwatson** [comment]
Ok, give it another try later on and post in here the error you are getting

**Comment by JPry** [comment]
I was having this exact same problem, which persisted even after following all of the steps suggested above. I was finally able to figure out what was happening. According to Valet+, I was supposed to be running `valet-php` version 7.1. To confirm this, I put in `phpinfo()` followed by `exit` in the `server.php` file before the error was triggered. It showed that the server was running PHP 7.2.

I decided to look at Homebrew services. This is what I got back:

```
brew services list
Name          Status  User Plist
dnsmasq       started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mailhog       started jpry /Users/jpry/Library/LaunchAgents/homebrew.mxcl.mailhog.plist
mariadb       started jpry /Users/jpry/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
memcached     started jpry /Users/jpry/Library/LaunchAgents/homebrew.mxcl.memcached.plist
nginx         started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php           stopped
php@7.2       started root /Library/LaunchDaemons/homebrew.mxcl.php@7.2.plist
redis         started jpry /Users/jpry/Library/LaunchAgents/homebrew.mxcl.redis.plist
valet-php@7.1 started root /Library/LaunchDaemons/homebrew.mxcl.valet-php@7.1.plist
valet-php@7.2 stopped
valet-php@7.3 stopped
```

While `valet-php@7.1` is indeed running, I *also* somehow had `php@7.2` running as well. I then ran the following (sudo was needed because the report above indicated it was running as root):

```
sudo brew services stop php@7.2
```

Once I did this, the fatal error around `apcu_fetch()` went away. For those others experiencing this error, I'd recommend checking Homebrew services to see if there's a conflict similar to what I found.

**Comment by MikeiLL** [comment]
Same issue on High Sierra. I tried the [above solution](https://github.com/weprovide/valet-plus/issues/284#issuecomment-458586140) 

```
brew reinstall openssl
pecl install apcu_bc
valet fix && valet install
```
and am back to:
```
[nginx] Restarting
Setting password for root user failed.
```
As referenced [#270](https://github.com/weprovide/valet-plus/issues/270), I've reinstalled MySQL at least half a dozen times using [this method](https://github.com/weprovide/valet-plus/issues/270#issuecomment-478147813). Then when I have reinstalled it's back to

```
Call to undefined function apcu_fetch()
```
I'm using [wp valet command](https://github.com/aaemnnosttv/wp-cli-valet-command) to create the (bedrock) file system and database, but don't imagine that has much to do with it.

Sorry I don't have any solutions yet.

**Comment by MikeiLL** [comment]
It must be that either [apcu](https://www.php.net/manual/en/function.apcu-fetch.php) isn't installed or isn't configured correctly and/or is in the wrong place.

```
$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
apcu    5.1.17  stable
apcu_bc 1.0.5   stable
geoip   1.1.1   beta
$ which pecl
/usr/local/bin/pecl
$ ls -l /usr/local/bin/pecl
lrwxr-xr-x  1 mikekilmer  wheel    39B Jun  9 01:08 /usr/local/bin/pecl@ -> ../Cellar/valet-php@7.1/7.1.26/bin/pecl
```
Is it because I have `extension`s [commented out](https://github.com/weprovide/valet-plus/issues/366#issuecomment-500144391) in `/usr/local/etc/valet-php/7.1/php.ini`? No look, their back. And it doesn't seem to make a difference if they're commented out or not.

They are supposedly enabled.
```
[PECL] Installing extensions
	apcu_bc is already installed, skipping...
	apcu_bc is already enabled, skipping...
	geoip is already installed, skipping...
	geoip is already enabled, skipping...
```
Doesn't look like php thinks the module is installed:

```
php --modules | grep 'apcu'
(nothing)
```

Ah. But when they aren't commented out in the `php.ini` file, and after `valet restart`, 
```
$ php --modules | grep 'apcu'
apcu
```

I also see `apc` and `geoip`, if they are there in the `php.ini`.

But I don't see a reference to `apcu_bc`.

There's an inconsistency between `pecl list` and the content of the extensions directory:
```
$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
apcu    5.1.17  stable
apcu_bc 1.0.5   stable
geoip   1.1.1   beta
mikekilmer@jamaaladeen-8:~$ ls /usr/local/lib/php/pecl/20160303/
apc.so    apcu.so   geoip.so
```

**Comment by lfolco** [comment]
I had an issue where the extensions were not added to my php.ini files. Adding the following lines fixed it:

```
extension="yaml.so"
extension="geoip.so"
extension="apcu.so"
extension="apc.so"
```

**Comment by diazwatson** [comment]
I had this issue again when installing in a new Mac and the way I used to fix it before did not work.
I finally manage to fix the issue by following the steps described by @isholaomotayo in here: 
https://github.com/weprovide/valet-plus/issues/275#issuecomment-536930084

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
