### ISSUE TITLE
Cannot install valet plus 2.x-dev version: "Could not find installation path for: apcu_bc"

### ISSUE THREAD

**Issue by frimipiso** [weprovide/valet-plus#443]
Hi,

I cannot install the valet plus 2.x-dev version on my mid 2010 mac mini with High Sierra.

I followed the original installation instructions except that I required the 2.x-dev version:

```
brew update
brew tap henkrehorst/php
brew install valet-php@7.2
brew install composer
composer require weprovide/valet-plus:2.x-dev
I added the composer path
valet fix
valet install
```

After entering the valet install command I get the following error message:

```
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions

In Pecl.php line 148:
                                                            
  Could not find installation path for: apcu_bc             
                                                            
  No releases available for package "pecl.php.net/apcu_bc"  
  install failed                                            
                        
```                                    

I have no idea what I can do. I never had a working valet+ installation so I am not upgrading. 

When I try to apply the upgrade instructions I just get the message that apcu is not installed:  https://github.com/weprovide/valet-plus/blob/2.x/UPGRADE-2.0.md

So what can I do? Am I the only one having these problems?
Has anyone actually installed valet+ in the last year?
It seems to be impossible to bypass the apcu problems no matter whether I install version 1 or version 2 of valet+.

Thanks

Jens

**Comment by muckz** [comment]
Hi Jens,
this is a problem with the ssl-cert of the pecl.php.net site.
I fixed this with the following steps:

1. Reinstall openssl
`brew reinstall openssl`

2. Link the cert.pem to the place where pecl looks for it
`ln -s /usr/local/etc/openssl@1.1/cert.pem /usr/local/etc/openssl/cert.pem`

3. Download the missing cert for the page from https://curl.haxx.se/ca/cacert.pem and copy it into the folder
`/usr/local/etc/openssl@1.1/certs`

4. Rehash the certs
`/usr/local/opt/openssl@1.1/bin/c_rehash`

5. Check if it works by running the pecl update channel command

6. Move forward to install valet
`valet install`

I just had this error myself and fixed it with those steps... hopefully I left nothing out. Good look!

**Comment by Ansiem** [comment]
> Hi Jens,
> this is a problem with the ssl-cert of the pecl.php.net site.
> I fixed this with the following steps:
> 
> 1. Reinstall openssl
>    `brew reinstall openssl`
> 2. Link the cert.pem to the place where pecl looks for it
>    `ln -s /usr/local/etc/openssl@1.1/cert.pem /usr/local/etc/openssl/cert.pem`
> 3. Download the missing cert for the page from https://curl.haxx.se/ca/cacert.pem and copy it into the folder
>    `/usr/local/etc/openssl@1.1/certs`
> 4. Rehash the certs
>    `/usr/local/opt/openssl@1.1/bin/c_rehash`
> 5. Check if it works by running the pecl update channel command
> 6. Move forward to install valet
>    `valet install`
> 
> I just had this error myself and fixed it with those steps... hopefully I left nothing out. Good look!

Unfortunatly this didn't work for me..
Still getting the same error.

**Comment by frimipiso** [comment]
Thanks muckz for the hint!

But it did not work for me. I was talk in another thread that Valet+ 2.x solves the apcu_bc problem,
but apparently it is still there.

After spending an enormous amount of time trying to install Valet+, **I am finally giving up**.
It sounded like a great idea, but apparently it is **impossible for mortals like myself** to install
Valet+.

Too bad, but it is time to move on ...

I will now use Mamp Pro on the Mac and Vagrant on my PC for website prototyping and debugging.

I will watch this thread but invest no more time into Valet+ until a **proper up-to-date manual** for 
installation is available.

Thanks

Jens

**Comment by nerotic** [comment]
I found a couple of issues I was able to work around:

> Download the missing cert for the page from https://curl.haxx.se/ca/cacert.pem and copy it into the folder /usr/local/etc/openssl@1.1/certs

You'll need to rename cacert.pem to cert.pem

> Check if it works by running the pecl update channel command

pecl channel-update pecl.php.net `  worked for me

By doing those two things I was able to get past:

>  Could not find installation path for: apcu_bc             
>                                                             
>   No releases available for package "pecl.php.net/apcu_bc"  
>   install failed      


Now I'm stuck here :                                                                                                                        

>  Could not find ini definition for: apcu_bc in PHP Warning:  Module 'apcu' already loaded in Unknown on line 0Warning: Module 'apcu' already loaded in Unknown on line 0/usr/local/etc/valet-php/7.2/php.ini  


So with no intention of hijacking this thread I will briefly mention that I've tried with valet+ 2 and have gotten this far with barely a hiccup

> nerotic@nerotics-MacBook-Pro ~ % valet install
> [php] Checking for errors within the php installation...
> [nginx] Stopping
> [valet-php@7.1] Stopping
> [valet-php@7.2] Stopping
> [mysql@5.7] Stopping
> [devtools] Installing tools
> [devtools] wp-cli already installed
> [devtools] pv already installed
> [devtools] geoip already installed
> [binaries] Installing binaries
> [BREW TAP] henkrehorst/php already installed
> [PECL] Updating PECL channel: pecl.php.net
> [PECL] Installing extensions
> 	apcu_bc is already installed, skipping...
> 	apcu_bc successfully enabled
> 	geoip successfully installed
> 	geoip is already enabled, skipping...
> 	yaml successfully installed
> 	yaml is already enabled, skipping...
> [PECL-CUSTOM] Installing extensions
> [valet-php@7.1] Restarting
> [dnsmasq] Installing
> [dnsmasq] Restarting
> [mysql@5.7] Installing
> [mysql-utilities] Installing
> Error: No available formula with the name "mysql-utilities" 
> ==> Searching for a previously deleted formula (in the last month)...
> Warning: homebrew/core is shallow clone. To get complete history run:
>   git -C "$(brew --repo homebrew/core)" fetch --unshallow
> 
> Error: No previously deleted formula found.
> Error: No similarly named formulae found.
> ==> Searching taps on GitHub...
> ==> Searching for similarly named formulae...
> ==> Searching taps...
> Error: No formulae found in taps.
> 
> 
> In Brew.php line 107:
>                                                  
>   Brew was unable to install [mysql-utilities].  
>                                                  
> 
> install [--with-mariadb]

Working on resolving this last bit [(https://github.com/weprovide/valet-plus/issues/436#issuecomment-580335782)]

**Comment by Neodork** [comment]
Hi!

We've fixed the dependency on the deprecated APCU_BC PECL extension.

This has been merged in `2.x` and will be released in version `2.0.0`.

See https://github.com/weprovide/valet-plus/pull/401 for more information.

Note: If you have an `1.0.x` installation and you're moving to `2.x` to fix the APCU_BC issues. Please follow the upgrade path https://github.com/weprovide/valet-plus/blob/2.x/UPGRADE-2.0.md.
